using Microsoft.Extensions.DependencyInjection;
using MossAgent.Application.Persistence;
using MossAgent.Browser;
using MossAgent.Browser.Tools;
using MossAgent.Mcp;
using MossAgent.Application.Models;
using MossAgent.Application.Agent;
using MossAgent.Application.Artifacts;
using MossAgent.Application.Networking;
using MossAgent.App.ViewModels;
using MossAgent.Infrastructure.Persistence;
using MossAgent.Infrastructure.Networking;
using MossAgent.Infrastructure.Git;
using MossAgent.Application.Git;
using MossAgent.Providers;
using MossAgent.Providers.OpenAi;
using MossAgent.Providers.Anthropic;
using MossAgent.Providers.Gemini;
using MossAgent.Agent;
using MossAgent.Tools.Abstractions;
using MossAgent.Tools.Abstractions.Browser;
using MossAgent.Tools.BuiltIn.Execution;
using MossAgent.Tools.BuiltIn.Files;
using MossAgent.Tools.BuiltIn.Processes;
using MossAgent.Tools.BuiltIn.Git;
using MossAgent.Platform.Windows.Capture;
using MossAgent.Platform.Windows.Terminal;
using MossAgent.Tools.Abstractions.Terminal;
using MossAgent.App.Browser;
using MossAgent.App.Services;

namespace MossAgent.App;

internal static class AppComposition
{
    public static ServiceProvider CreateServices()
    {
        var services = new ServiceCollection();
        services.AddSingleton<AppDataPaths>();
        services.AddSingleton<SqliteConnectionFactory>();
        services.AddSingleton<IDatabaseInitializer, SqliteDatabaseInitializer>();
        services.AddSingleton<IConfigurationRepository, SqliteConfigurationRepository>();
        services.AddSingleton<IBrowserConfigurationRepository, SqliteBrowserConfigurationRepository>();
        services.AddSingleton<IMcpConfigurationRepository, SqliteMcpConfigurationRepository>();
        services.AddSingleton<IWorkspaceRepository, SqliteWorkspaceRepository>();
        services.AddSingleton<ITaskArtifactPaths, TaskArtifactPaths>();
        services.AddSingleton<IBrowserProfilePaths, BrowserProfilePaths>();
        services.AddSingleton<IGitWorktreeService, GitWorktreeService>();
        services.AddSingleton<IProviderHttpClientFactory, ProviderHttpClientFactory>();
        services.AddSingleton<IProxyConnectionTester, ProxyConnectionTester>();
        services.AddSingleton<IToolExecutionAuditSink, SqliteToolExecutionAuditSink>();
        services.AddSingleton<IToolExecutionAuditReader, SqliteToolExecutionAuditReader>();
        services.AddSingleton<IModelDiscoveryService, ModelDiscoveryService>();
        services.AddSingleton<OpenAiResponsesProvider>();
        services.AddSingleton<IModelProvider>(static provider => provider.GetRequiredService<OpenAiResponsesProvider>());
        services.AddSingleton<IModelProvider, OpenAiCompatibleProvider>();
        services.AddSingleton<IModelProvider, AnthropicMessagesProvider>();
        services.AddSingleton<IModelProvider, GeminiGenerateContentProvider>();
        services.AddSingleton<IModelProviderRegistry, ModelProviderRegistry>();
        services.AddSingleton<AuthorizedPathResolver>();
        services.AddSingleton<GitCommandRunner>();
        services.AddSingleton<IBrowserSessionFactory, PlaywrightBrowserSessionFactory>();
        services.AddSingleton<EmbeddedBrowserPaneViewModel>();
        services.AddSingleton<IEmbeddedBrowserSessionFactory, EmbeddedBrowserSessionFactory>();
        services.AddSingleton<ITaskBrowserSessionManager, TaskBrowserSessionManager>();
        services.AddSingleton<ITerminalSessionManager, PtyTerminalSessionManager>();
        services.AddSingleton<IAgentTool, FileReadTool>();
        services.AddSingleton<IAgentTool, DirectoryListTool>();
        services.AddSingleton<IAgentTool, FileWriteTool>();
        services.AddSingleton<IAgentTool, TextReplaceTool>();
        services.AddSingleton<IAgentTool, SearchTextTool>();
        services.AddSingleton<IAgentTool, FileFindTool>();
        services.AddSingleton<IAgentTool, DirectoryCreateTool>();
        services.AddSingleton<IAgentTool, PathCopyTool>();
        services.AddSingleton<IAgentTool, PathMoveTool>();
        services.AddSingleton<IAgentTool, PathDeleteTool>();
        services.AddSingleton<IAgentTool, ShellRunTool>();
        services.AddSingleton<IAgentTool, GitStatusTool>();
        services.AddSingleton<IAgentTool, GitDiffTool>();
        services.AddSingleton<IAgentTool, GitLogTool>();
        services.AddSingleton<IAgentTool, GitCreateWorktreeTool>();
        services.AddSingleton<IAgentTool, BrowserNavigateTool>();
        services.AddSingleton<IAgentTool, BrowserTabsTool>();
        services.AddSingleton<IAgentTool, BrowserNewTabTool>();
        services.AddSingleton<IAgentTool, BrowserSwitchTabTool>();
        services.AddSingleton<IAgentTool, BrowserCloseTabTool>();
        services.AddSingleton<IAgentTool, BrowserBackTool>();
        services.AddSingleton<IAgentTool, BrowserForwardTool>();
        services.AddSingleton<IAgentTool, BrowserReloadTool>();
        services.AddSingleton<IAgentTool, BrowserSnapshotTool>();
        services.AddSingleton<IAgentTool, BrowserClickTool>();
        services.AddSingleton<IAgentTool, BrowserTypeTool>();
        services.AddSingleton<IAgentTool, BrowserWaitTool>();
        services.AddSingleton<IAgentTool, BrowserSelectTool>();
        services.AddSingleton<IAgentTool, BrowserScrollTool>();
        services.AddSingleton<IAgentTool, BrowserScreenshotTool>();
        services.AddSingleton<IAgentTool, BrowserDownloadTool>();
        services.AddSingleton<IAgentTool, ScreenCaptureTool>();
        services.AddSingleton<IAgentTool, TerminalStartTool>();
        services.AddSingleton<IAgentTool, TerminalWriteTool>();
        services.AddSingleton<IAgentTool, TerminalResizeTool>();
        services.AddSingleton<IAgentTool, TerminalStopTool>();
        services.AddSingleton<ToolRegistry>();
        services.AddSingleton<IToolCatalog>(static provider => provider.GetRequiredService<ToolRegistry>());
        services.AddSingleton<IMutableToolCatalog>(static provider => provider.GetRequiredService<ToolRegistry>());
        services.AddSingleton<McpHttpClientFactory>();
        services.AddSingleton<IMcpManager, McpManager>();
        services.AddSingleton<ApprovalViewModel>();
        services.AddSingleton<IToolApprovalService>(provider =>
        {
            var approval = provider.GetRequiredService<ApprovalViewModel>();
            return new PolicyApprovalService(approval.RequestAsync);
        });
        services.AddSingleton<IToolExecutor, ToolExecutor>();
        services.AddSingleton<IAgentRunner, AgentRunner>();
        services.AddSingleton<ProxySettingsViewModel>();
        services.AddSingleton<ProviderSettingsViewModel>();
        services.AddSingleton<ModelSettingsViewModel>();
        services.AddSingleton<WorkspaceTaskFactory>();
        services.AddSingleton<WorkspaceRunTracker>();
        services.AddSingleton<WorkspaceRunExecutor>();
        services.AddSingleton<WorkspaceRunController>();
        services.AddSingleton<WorkspaceTaskPanelCoordinator>();
        services.AddSingleton<WorkspaceWorktreeCleanupService>();
        services.AddSingleton<WorkspaceCatalogViewModel>();
        services.AddSingleton<TerminalPaneViewModel>();
        services.AddSingleton<DiffPaneViewModel>();
        services.AddSingleton<AuditPaneViewModel>();
        services.AddSingleton<BrowserSettingsViewModel>();
        services.AddSingleton<McpSettingsViewModel>();
        services.AddSingleton<WorkspaceViewModel>();
        services.AddSingleton<IThemeService, ThemeService>();
        services.AddSingleton<MainWindowViewModel>();
        return services.BuildServiceProvider(validateScopes: true);
    }
}
