<Project Sdk="Microsoft.NET.Sdk">
  <ItemGroup>
    <ProjectReference Include="../MossAgent.Application/MossAgent.Application.csproj" />
    <ProjectReference Include="../MossAgent.Tools.Abstractions/MossAgent.Tools.Abstractions.csproj" />
    <PackageReference Include="Microsoft.Playwright" />
  </ItemGroup>
</Project>
