<Project Sdk="Microsoft.NET.Sdk">
  <ItemGroup>
    <ProjectReference Include="../MossAgent.Application/MossAgent.Application.csproj" />
    <PackageReference Include="Microsoft.Extensions.Http" />
  </ItemGroup>
  <ItemGroup>
    <AssemblyAttribute Include="System.Runtime.CompilerServices.InternalsVisibleToAttribute">
      <_Parameter1>MossAgent.Providers.Tests</_Parameter1>
    </AssemblyAttribute>
  </ItemGroup>
</Project>
